# Generated by Django 2.1.2 on 2018-10-01 20:19

from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='domain',
            managers=[
                ('objects', domains.models.DomainManager()),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=128, unique=True, validators=[domains.models._simple_domain_name_validator]),
        ),
    ]
